name: publish slides

on:
  push:
    branches:
      - main

jobs:
  deploy-ghpages:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Collect slides 📦
        run: |
          shopt -s extglob
          mkdir archive/gh-pages
          cp -rL archive/!(gh-pages) archive/gh-pages
      - name: Build 🔨
        run: |
          find . | grep ".zip" | tr "\n" "\0" | xargs -0 rm
          # maybe useful in future for publishing pdf files
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.PUBLISH_SITE }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: "archive/gh-pages" # The folder the action should deploy.
