name: publish slides

on:
  push:
    branches:
      - master

jobs:
  deploy-ghpages:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          token: ${{ secrets.PUBLISH_SITE }}
          submodules: "true"
      - name: Collect slides 📦
        run: |
          mkdir archive/gh-pages
          cp -L archive/* archive/gh-pages
      - name: Build 🔨
        run: |
          # not used currently
          # maybe useful in future for publishing pdf files
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.PUBLISH_SITE }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: "archive/gh-pages" # The folder the action should deploy.
